data:
  augmentation:
    color_jitter: true
    cutout: true
    random_crop: true
    random_flip: true
  batch_size: 128
  data_path: ./data
  dataset: cifar
  normalization:
    mean:
    - 0.4914
    - 0.4822
    - 0.4465
    std:
    - 0.247
    - 0.2435
    - 0.2616
  num_workers: 4
  persistent_workers: true
  pin_memory: true
  prefetch_factor: 2
device: cuda
experiment_name: default
logging:
  log_dir: ./logs
  log_level: INFO
  save_frequency: 5
  track_grad_norm: true
  wandb: false
  wandb_entity: null
  wandb_project: adaptive-cnn
model:
  architecture: []
  classifier_layers: []
  dropout: 0.5
  in_channels: 3
  model_type: adaptive_cnn
  num_classes: 10
  use_se: true
output_dir: ./outputs
seed: 42
training:
  amp_backend: native
  early_stopping: true
  early_stopping_min_delta: 0.001
  early_stopping_patience: 10
  gradient_accumulation_steps: 1
  gradient_clip_val: 1.0
  label_smoothing: 0.1
  learning_rate: 0.1
  lr_scheduler_params:
    T_max: 200
    eta_min: 0.0001
  num_epochs: 200
  optimizer: sgd
  scheduler: cosine
  swa_lr: 0.0005
  swa_start_epoch: 0.75
  use_amp: true
  use_swa: true
  warmup_epochs: 10
  weight_decay: 0.0005
